permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: qingwei pan
  email: pqwggm@163.com
  link: http://pqwggm.github.io/
  weibo: http://weibo.com/panqingwei
  github: https://github.com/pqwggm
#  music: http://site.douban.com/linanya
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 潘清伟的博客
description: My personal blog
url: https://pqwggm.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/pqw1.jpg
favicon: /public/img/pqw1.jpg

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
#disqus:
#  shortname: painterlin

# 多说 设置
# comments:
#  provider: duoshuo
#  duoshuo:
#    short_name: pqwggm1

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
#cates: 
#  - Optimization
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  words: 留言
